import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Target, Flame, Sparkles, TrendingUp, BarChart3, Bell, CheckCircle, ArrowRight, Star } from "lucide-react";
import { AnimatedSection } from "@/components/landing/AnimatedSection";
import { InteractiveDemo } from "@/components/landing/InteractiveDemo";
import { useTheme } from "next-themes";
import { useEffect } from "react";

const features = [
  {
    icon: Target,
    title: "Goal Tracking",
    description: "Set meaningful goals with deadlines and track your progress with visual indicators that keep you motivated.",
  },
  {
    icon: Flame,
    title: "Habit Streaks",
    description: "Build powerful habits with daily check-ins. Watch your streaks grow and never break the chain.",
  },
  {
    icon: Sparkles,
    title: "AI Motivation",
    description: "Get personalized daily quotes generated by AI, tailored to your interests and current goals.",
  },
  {
    icon: BarChart3,
    title: "Progress Analytics",
    description: "Visualize your journey with beautiful charts showing completion rates, streaks, and achievements.",
  },
];

const steps = [
  { number: "01", title: "Set Your Goals", description: "Define what matters to you with clear, actionable goals" },
  { number: "02", title: "Build Habits", description: "Create daily habits that move you closer to your goals" },
  { number: "03", title: "Track Progress", description: "Check in daily and watch your streaks grow" },
  { number: "04", title: "Stay Inspired", description: "Get AI-powered motivation customized just for you" },
];

const testimonials = [
  {
    quote: "GrowthPath helped me build a consistent morning routine. I'm on a 45-day streak!",
    author: "Sarah K.",
    role: "Product Designer",
  },
  {
    quote: "The AI quotes are surprisingly personal. It's like having a coach who knows exactly what I need to hear.",
    author: "Marcus T.",
    role: "Entrepreneur",
  },
  {
    quote: "Finally, a goal tracker that's beautiful AND functional. I've completed 8 goals in 3 months.",
    author: "Elena R.",
    role: "Software Engineer",
  },
];

export default function Landing() {
  const { setTheme } = useTheme();

  useEffect(() => {
    setTheme("light");
  }, [setTheme]);

  const scrollToDemo = () => {
    document.getElementById("demo-section")?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className="min-h-screen bg-background overflow-hidden relative">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-border/20 backdrop-blur-2xl bg-background/80">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center">
              <Target className="w-5 h-5 text-primary-foreground" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-foreground">GrowthPath</h1>
              <p className="text-xs text-muted-foreground hidden sm:block">Track • Grow • Achieve</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/auth">
              <Button variant="ghost" className="rounded-xl">Sign In</Button>
            </Link>
            <Link to="/auth">
              <Button className="rounded-xl bg-gradient-to-r from-primary to-accent hover:opacity-90">
                Get Started
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-4 relative">
        {/* Background decorations */}
        <div className="absolute top-20 left-10 w-72 h-72 bg-primary/6 rounded-full blur-[100px] animate-pulse-soft" />
        <div className="absolute top-40 right-10 w-96 h-96 bg-accent/5 rounded-full blur-[100px] animate-pulse-soft" style={{ animationDelay: '2s' }} />
        <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-secondary/5 rounded-full blur-[120px] animate-pulse-soft" style={{ animationDelay: '4s' }} />

        <div className="container mx-auto text-center relative z-10">
          <AnimatedSection animation="fade-in">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
              <Sparkles className="w-4 h-4" />
              AI-Powered Personal Growth
            </div>
          </AnimatedSection>

          <AnimatedSection animation="fade-up" delay={100}>
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold text-foreground mb-6 leading-tight">
              Transform Your Goals
              <br />
              <span className="gradient-text">Into Achievements</span>
            </h1>
          </AnimatedSection>

          <AnimatedSection animation="fade-up" delay={200}>
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10">
              Track habits, set goals, and stay motivated with personalized AI-generated
              inspiration. Build the life you've always wanted, one day at a time.
            </p>
          </AnimatedSection>

          <AnimatedSection animation="fade-up" delay={300}>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link to="/auth">
                <Button size="lg" className="rounded-xl h-14 px-8 text-lg bg-gradient-to-r from-primary to-accent hover:opacity-90 shadow-glow">
                  Start Your Journey
                  <ArrowRight className="w-5 h-5 ml-2" />
                </Button>
              </Link>
              <Button
                size="lg"
                variant="outline"
                className="rounded-xl h-14 px-8 text-lg"
                onClick={scrollToDemo}
              >
                Try Demo
              </Button>
            </div>
          </AnimatedSection>

          {/* Stats */}
          <AnimatedSection animation="fade-up" delay={400}>
            <div className="flex flex-wrap items-center justify-center gap-8 mt-16">
              <div className="text-center">
                <p className="text-3xl font-bold text-foreground">10K+</p>
                <p className="text-sm text-muted-foreground">Active Users</p>
              </div>
              <div className="w-px h-12 bg-border hidden sm:block" />
              <div className="text-center">
                <p className="text-3xl font-bold text-foreground">500K+</p>
                <p className="text-sm text-muted-foreground">Goals Completed</p>
              </div>
              <div className="w-px h-12 bg-border hidden sm:block" />
              <div className="text-center">
                <p className="text-3xl font-bold text-foreground">2M+</p>
                <p className="text-sm text-muted-foreground">Habits Tracked</p>
              </div>
            </div>
          </AnimatedSection>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 surface-container">
        <div className="container mx-auto">
          <AnimatedSection className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              Everything You Need to <span className="gradient-text">Succeed</span>
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Powerful features designed to help you build better habits and achieve your goals faster.
            </p>
          </AnimatedSection>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => (
              <AnimatedSection key={feature.title} delay={index * 100}>
                <div className="glass-card rounded-2xl p-6 hover:shadow-glow transition-all duration-300 hover:-translate-y-1 h-full">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center mb-4">
                    <feature.icon className="w-6 h-6 text-primary-foreground" />
                  </div>
                  <h3 className="text-lg font-semibold text-foreground mb-2">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </div>
              </AnimatedSection>
            ))}
          </div>
        </div>
      </section>

      {/* Interactive Demo Section */}
      <div id="demo-section">
        <InteractiveDemo />
      </div>

      {/* How It Works */}
      <section className="py-20 px-4 surface-container">
        <div className="container mx-auto">
          <AnimatedSection className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              How <span className="gradient-text">GrowthPath</span> Works
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Simple steps to transform your daily routine and achieve lasting change.
            </p>
          </AnimatedSection>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((step, index) => (
              <AnimatedSection key={step.number} delay={index * 100}>
                <div className="relative text-center">
                  <div className="text-6xl font-bold text-primary/10 mb-4">{step.number}</div>
                  <h3 className="text-lg font-semibold text-foreground mb-2">{step.title}</h3>
                  <p className="text-sm text-muted-foreground">{step.description}</p>
                  {index < steps.length - 1 && (
                    <div className="hidden lg:block absolute top-8 left-full w-full h-px bg-gradient-to-r from-primary/30 to-transparent" />
                  )}
                </div>
              </AnimatedSection>
            ))}
          </div>
        </div>
      </section>

      {/* AI Quote Preview */}
      <section className="py-20 px-4">
        <div className="container mx-auto">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <AnimatedSection animation="slide-right">
              <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
                <span className="gradient-text">AI-Powered</span>
              </h2>
              <p className="text-muted-foreground mb-6">
                Our AI learns your interests and goals to deliver personalized quotes that resonate
                with your journey. Every morning, receive inspiration crafted just for you.
              </p>
              <ul className="space-y-3">
                {[
                  "Personalized to your interests",
                  "Tailored to your current goals",
                  "Fresh quotes every day",
                  "Mix of famous and original quotes",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-3 text-foreground">
                    <CheckCircle className="w-5 h-5 text-secondary" />
                    {item}
                  </li>
                ))}
              </ul>
            </AnimatedSection>
            <AnimatedSection animation="slide-left" delay={200}>
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-to-br from-primary/20 to-accent/20 rounded-3xl blur-2xl" />
                <div className="relative rounded-2xl p-8 bg-gradient-to-br from-primary via-primary/90 to-accent text-primary-foreground shadow-glow">
                  <div className="flex items-center gap-2 mb-6">
                    <Sparkles className="w-5 h-5 animate-pulse-soft" />
                    <span className="text-sm font-medium opacity-90">Daily Motivation • Productivity</span>
                  </div>
                  <blockquote className="text-xl md:text-2xl font-semibold leading-relaxed mb-4">
                    "Small daily improvements over time lead to stunning results. Focus on progress, not perfection."
                  </blockquote>
                  <p className="text-sm opacity-80 font-medium">— Robin Sharma</p>
                </div>
              </div>
            </AnimatedSection>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 px-4 surface-container">
        <div className="container mx-auto">
          <AnimatedSection className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              Loved by <span className="gradient-text">Thousands</span>
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              See what our community says about their transformation journey.
            </p>
          </AnimatedSection>

          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((testimonial, index) => (
              <AnimatedSection key={testimonial.author} delay={index * 100}>
                <div className="glass-card rounded-2xl p-6 h-full">
                  <div className="flex gap-1 mb-4">
                    {[...Array(5)].map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-primary text-primary" />
                    ))}
                  </div>
                  <p className="text-foreground mb-4">"{testimonial.quote}"</p>
                  <div>
                    <p className="font-semibold text-foreground">{testimonial.author}</p>
                    <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                  </div>
                </div>
              </AnimatedSection>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto">
          <AnimatedSection animation="scale">
            <div className="relative rounded-3xl p-12 bg-gradient-to-br from-primary via-primary/90 to-accent text-primary-foreground text-center overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-primary-foreground/10 rounded-full -translate-y-1/2 translate-x-1/2" />
              <div className="absolute bottom-0 left-0 w-48 h-48 bg-primary-foreground/5 rounded-full translate-y-1/2 -translate-x-1/2" />

              <div className="relative z-10">
                <h2 className="text-3xl md:text-4xl font-bold mb-4">
                  Ready to Start Your Growth Journey?
                </h2>
                <p className="text-lg opacity-90 max-w-xl mx-auto mb-8">
                  Join thousands of people who are already achieving their goals and building better habits.
                </p>
                <Link to="/auth">
                  <Button size="lg" variant="secondary" className="rounded-xl h-14 px-8 text-lg">
                    Get Started Free
                    <ArrowRight className="w-5 h-5 ml-2" />
                  </Button>
                </Link>
              </div>
            </div>
          </AnimatedSection>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-4 border-t border-border">
        <div className="container mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                <Target className="w-4 h-4 text-primary-foreground" />
              </div>
              <span className="font-semibold text-foreground">GrowthPath</span>
            </div>
            <p className="text-sm text-muted-foreground">
              © 2026 GrowthPath. Transform your goals into achievements.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
